name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Terraform state file exists
        run: |
          if aws s3 ls s3://your-bucket-name/path/to/your.tfstate; then
            echo "State file exists. Proceeding with destroy."
          else
            echo "No state file found. Skipping destroy."
            exit 0
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Plan Terraform changes
        run: terraform plan -destroy
        working-directory: infra

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: infra