name: Terraform AWS Infrastructure Workflow
on: 
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: infra

      - name: Plan Terraform changes
        run: terraform plan
        working-directory: infra

      # - name: Apply Terraform changes
      #   run: terraform apply -auto-approve